"""add_more_field_to_uploads

Revision ID: 24d4bb0eb800
Revises: 2d4dc644b7ff
Create Date: 2026-05-26 16:44:06.733688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '24d4bb0eb800'
down_revision: Union[str, Sequence[str], None] = '2d4dc644b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='filetypeenum'), nullable=False))
    op.add_column('uploaded_files', sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'file_hash')
    op.drop_column('uploaded_files', 'file_type')
    # ### end Alembic commands ###
