"""add_start_and_end_time_to_recordings

Revision ID: 6f2c37ed0807
Revises: ae2f683f9820
Create Date: 2026-05-29 11:46:17.772927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6f2c37ed0807'
down_revision: Union[str, Sequence[str], None] = 'ae2f683f9820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_recordings', sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('meeting_recordings', sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('meeting_speakers', sa.Column('speaker_embeddings', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_speakers', 'speaker_embeddings')
    op.drop_column('meeting_recordings', 'end_time')
    op.drop_column('meeting_recordings', 'start_time')
    # ### end Alembic commands ###
