"""added_account_loked

Revision ID: 75510606b51e
Revises: e75d5f5a352d
Create Date: 2026-05-25 10:06:22.126836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75510606b51e'
down_revision: Union[str, Sequence[str], None] = 'e75d5f5a352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'account_locked')
    # ### end Alembic commands ###
